apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod-argo-application
  namespace: argocd
spec:
    project: default
    source:
        chart: kubernetes-app
        repoURL: http://192.168.178.53:8150 # Make portforward to chartmuseum first.
        targetRevision: 0.*
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: myapp
    syncPolicy:
      syncOptions:
        - CreateNamespace=true

      automated:
        selfHeal: true
        prune: true
